import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/Header";
import HeroSection from "./_components/Hero Section/HeroSection";
import CategoryList from "./_components/Category/CategoryList";
import ProductList from "./_components/Product/ProductList";
import About from "./_components/About/About";
import Reviews from "./_components/Review/Reviews";
import Footer from "./_components/Footer/Footer";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const category = [
  {
    image : './categories/vegetables.png',
    name : 'Vegetables'
  },
  {
    image : './categories/fruit.png',
    name : 'Fruits'
  },
  {
    image : './categories/milk.png',
    name : 'Milk & Juice'
  },
  {
    image : './categories/bakery.png',
    name : 'Bakery'
  },
  {
    image : './categories/cream.png',
    name : 'Personal Care'
  },
  
  {
    image : './categories/wheat-sack.png',
    name : 'Grains'
  },
  {
    image : './categories/chicken.png',
    name : 'Chicken & Egg'
  }
]
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Header category={category}/>
        <HeroSection/>
        <CategoryList category={category}/>
        <ProductList/>
        <About/>
        <Reviews/>
        <Footer/>
      </body>
    </html>
  );
}
